language: java

matrix:
  include:
    - os: osx
      env:
        - NODE_VERSION=8
      # Use Java 8
      osx_image: xcode9.3
    - os: linux
      env:
        - NODE_VERSION=10
      jdk: openjdk8

# safelist
branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - $HOME/.m2

before_install:
  # Trigger an Appveyor windows build every time Travis runs a cron job
  - >
      if [ $TRAVIS_EVENT_TYPE = "cron" && $TRAVIS_OS_NAME = "linux" ]; then
        curl -H "Authorization: Bearer ${APPVEYOR_TOKEN}" -H "Content-Type application\/json" --request POST  --data '{"accountName":"ClosureCompilerProject","projectSlug":"closure-compiler-npm","branch":"master","environmentVariables":{"COMPILER_NIGHTLY":"1"}}' https://ci.appveyor.com/api/builds;
      fi
  - nvm install $NODE_VERSION
  - if [ $TRAVIS_OS_NAME = "linux" ]; then cp .travis-settings.xml ~/.m2/settings.xml; fi
  # On Mac OS, maven builds fail with a "Non-resolvable parent POM" error.
  # The fix is to copy a basic maven settings.xml file into the ~/.m2 folder
  # https://stackoverflow.com/a/36982050/1211524
  - if [ $TRAVIS_OS_NAME = "osx" ]; then cp .travis-settings.xml ~/.m2/settings.xml; fi
  # Install yarn version 1.16 by downloading its install script and executing it in bash
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  # For a cron job on travis, test the latest commit on the compiler submodule branch.
  # Disables tests ensuring the submodule is on a tagged commit.
  # Move the submodule pointer to the latest master branch commit.
  # Pipe the latest commit output through cat to log it to the console for debugging
  - if [ $TRAVIS_EVENT_TYPE = "cron" ]; then
      export COMPILER_NIGHTLY=1;
      cd compiler && git checkout master && git pull origin master && git log -1 | cat;
      cd ..;
    fi

install: yarn install --colors=always

before_script: yarn run build --colors=always

script: yarn test --colors

before_deploy:
  # The linux and osx packages need OS restrictions added to their package.json files.
  # This cannot be added before now or the workspace install breaks.
  - build-scripts/add-os-restrictions.js
  # If this is the daily cron job, create a nightly release version
  - if [ $COMPILER_NIGHTLY = "1" ]; then build-scripts/create-nightly-version.js; fi

deploy:
  skip_cleanup: true
  provider: script
  script: build-scripts/lerna-publish.js publish-travis --npm-client ${TRAVIS_BUILD_DIR}/build-scripts/npm-client.js --ignore-changes '**/*' --force-publish='*' --yes
  on:
    branch: master
