version: 1.0.{build}

image: Visual Studio 2015

clone_depth: 50

environment:
  PATH: C:\Program Files (x86)\Apache\Maven\bin;%PATH%

branches:
  only:
    - master

cache:
  - '%USERPROFILE%\.m2'
  - '%LOCALAPPDATA%\yarn\cache'

install:
  - "@echo on"
  - git submodule update --init --recursive
  - choco install nodejs --version 12.4.0
  - choco install yarn --version 1.16.0
  - yarn install --colors=always
  - IF "%COMPILER_NIGHTLY%" == "1" CD compiler
  - IF "%COMPILER_NIGHTLY%" == "1" git checkout master
  - IF "%COMPILER_NIGHTLY%" == "1" git pull origin master
  - IF "%COMPILER_NIGHTLY%" == "1" git log -1 | cat
  - IF "%COMPILER_NIGHTLY%" == "1" CD ..

build_script:
  - "@echo on"
  - node ./build-scripts/build_compiler.js --colors=always
  - yarn workspaces run build

test_script:
  - "echo on"
  - yarn workspaces run test --colors
  - node_modules/.bin/mocha --colors

deploy_script:
  - node build-scripts/add-os-restrictions.js
  - IF "%COMPILER_NIGHTLY%" == "1" node build-scripts/create-nightly-version.js
  - IF "%APPVEYOR_PULL_REQUEST_NUMBER%" == "" IF "%APPVEYOR_REPO_BRANCH%" == "master" node build-scripts/lerna-publish.js publish-travis --npm-client ${TRAVIS_BUILD_DIR}/build-scripts/npm-client.js --ignore-changes '**/*' --force-publish='*' --yes
