version: 1.0.{build}

image: Visual Studio 2019

clone_depth: 50

environment:
  PATH: C:\Program Files (x86)\Apache\Maven\bin;%PATH%

branches:
  only:
    - master

cache:
  - '%USERPROFILE%\.m2'
  - '%LOCALAPPDATA%\yarn\cache'

install:
  - "@echo on"
  - SET JAVA_HOME="C:\Program Files\java\jdk11"
  - SET PATH="C:\Program Files\java\jdk11\bin";%PATH%
  - echo %PATH%
  - git config --global user.email "ci@appveyor.com"
  - git config --global user.name "Appveyor"
  - git submodule update --init --recursive
  - choco install nodejs --version 12.4.0
  - choco install yarn
  - yarn install --colors=always
  - IF "%COMPILER_NIGHTLY%" == "1" CD compiler
  - IF "%COMPILER_NIGHTLY%" == "1" git checkout master
  - IF "%COMPILER_NIGHTLY%" == "1" git pull origin master
  - IF "%COMPILER_NIGHTLY%" == "1" git log -1 | cat
  - IF "%COMPILER_NIGHTLY%" == "1" CD ..

build_script:
  - "@echo on"
  - java -version
  - node ./build-scripts/build_compiler.js --colors=always
  - yarn workspaces run build

test_script:
  - "echo on"
  - yarn workspaces run test --colors
  - node_modules/.bin/mocha --colors

deploy_script:
  - node build-scripts/add-os-restrictions.js
  - IF "%COMPILER_NIGHTLY%" == "1" node build-scripts/create-nightly-version.js
  - IF "%APPVEYOR_PULL_REQUEST_NUMBER%" == "" IF "%APPVEYOR_REPO_BRANCH%" == "master" node build-scripts/lerna-publish.js publish-travis --npm-client "%APPVEYOR_BUILD_FOLDER%/build-scripts/npm-client.js" --ignore-changes "**/*" --force-publish="*" --yes
